<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>C_PlayersGuide</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject></StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Part1\**" />
    <Compile Remove="Part2\**" />
    <EmbeddedResource Remove="Part1\**" />
    <EmbeddedResource Remove="Part2\**" />
    <None Remove="Part1\**" />
    <None Remove="Part2\**" />
  </ItemGroup>

</Project>
